(source "melpa" "http://melpa.org/packages/")
(source gnu)
(source melpa)

(depends-on "ace-link")
(depends-on "achievements")
(depends-on "afternoon-theme")
(depends-on "async")
(depends-on "auctex")
(depends-on "avy")
(depends-on "beacon")
(depends-on "biblio")
(depends-on "biblio-core")
(depends-on "cask")
(depends-on "company")
(depends-on "company-auctex")
(depends-on "company-quickhelp")
(depends-on "dash")
(depends-on "dash-functional")
(depends-on "dired+")
(depends-on "dklrt")
(depends-on "dkmisc")
(depends-on "elpy")
(depends-on "epl")
(depends-on "f")
(depends-on "find-file-in-project")
(depends-on "flycheck")
(depends-on "git-commit")
(depends-on "git-timemachine")
(depends-on "haskell-mode")
(depends-on "helm")
(depends-on "helm-bibtex")
(depends-on "helm-core")
(depends-on "helm-descbinds")
(depends-on "helm-mu")
(depends-on "helm-projectile")
(depends-on "highlight-indentation")
(depends-on "highlight-tail")
(depends-on "hydra")
(depends-on "intero")
(depends-on "ivy")
(depends-on "key-chord")
(depends-on "keyfreq")
(depends-on "ledger-mode")
(depends-on "magit")
(depends-on "magit-popup")
(depends-on "markdown-mode")
(depends-on "markdown-mode+")
(depends-on "markdown-preview-eww")
(depends-on "markdown-preview-mode")
(depends-on "markdown-toc")
(depends-on "mu4e-maildirs-extension")
(depends-on "ob-ipython")
(depends-on "openwith")
(depends-on "org-bullets")
(depends-on "org-ref")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "parsebib")
(depends-on "pdf-tools")
(depends-on "pkg-info")
(depends-on "popup")
(depends-on "pos-tip")
(depends-on "projectile")
(depends-on "pyvenv")
(depends-on "rainbow-delimiters")
(depends-on "rich-minority")
(depends-on "s")
(depends-on "shut-up")
(depends-on "smart-mode-line")
(depends-on "smartparens")
(depends-on "smooth-scroll")
(depends-on "smooth-scrolling")
(depends-on "switch-window")
(depends-on "tablist")
(depends-on "undo-tree")
(depends-on "websocket")
(depends-on "win-switch")
(depends-on "with-editor")
(depends-on "yasnippet")







